# Default System Configs
system:
  ports:
    processing: 12000   
    supercollider: 57120
    teensy: "COM6"  # Change this to match your actual COM port
  paths:
    processing_win: "C:\\Users\\carte\\Downloads\\processing-4.3-windows-x64\\processing-4.3\\processing-java.exe"
    processing_alt_win: "C:\\Program Files\\processing-4.3\\processing-java.exe"
    processing_mac: "/Applications/Processing.app/Contents/MacOS/processing-java"
    supercollider_win: "C:\\Program Files\\SuperCollider-3.13.0\\sclang.exe"
  defaults:
    baud_rate: 115200  # Updated for new Teensy code
    initial_mode: "build-a-synth" 

modes:
  Wizardcore:
    description: "Wizard mode with fireballs and magic missiles"
    processing:
      sketch: "wizardcore"
      commands:
        fireball: "/fireball"
        missile: "/missile"
        pot_control: "/potControl"
    supercollider:
      script: "wizardcore.scd"
      commands:
        kick: "/kick"
        sine: "/sine_t"
    controls:
      buttons:
        btn1:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/sine_t"
              params: [440]
            - target: "processing"
              command: "/missile"
              params: [3]
        btn2:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/kick"
              params: [300]
            - target: "processing"
              command: "/fireball"
              params: [5]
        btn3:  # Mode switch button
          type: "system"
          description: "Mode switch button"
        # New direct buttons
        btn4:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/sine_t"
              params: [880]
        btn5:
          type: "effect"
          actions:
            - target: "processing"
              command: "/fireball"
              params: [2]
        btn6:
          type: "effect"
          actions:
            - target: "processing"
              command: "/missile"
              params: [1]
        btn7:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/kick"
              params: [150]
        # Matrix buttons (examples)
        mbtn1:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/sine_t"
              params: [220]
        mbtn2:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/sine_t"
              params: [330]
      pots:
        pot1:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [0]
        pot2:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [1]
        pot3:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [2]
  main-menu:
    description: "Idle screen for when I am not showcasing"
    processing:
      sketch: "main_menu"
      commands:
        idle: "/idle"  # Placeholder for future commands
    supercollider:
      script: "main-menu.scd"
      commands:
        idle: "/idle"  # Placeholder for future commands
    controls:
      buttons:
      btn3:
        type: "system"
        description: "Mode switch button"
  build-a-synth:
    description: "Allows the user to choose and edit the parameters of a synth"
    processing:
      sketch: "build_a_synth"
      commands:
        idle: "/idle" # Placeholder for future commands
    supercollider:
      script: "build-a-synth.scd"
      commands:
        idle: "/idle" # Placeholder for future commands