# Default System Configs
system:
  ports:
    processing: 12000   
    supercollider: 57120
    teensy: "COM6"
  paths:
    processing_win: "C:\\Users\\carte\\Downloads\\processing-4.3-windows-x64\\processing-4.3\\processing-java.exe"
    processing_alt_win: "C:\\Program Files\\processing-4.3\\processing-java.exe"
    processing_mac: "/Applications/Processing.app/Contents/MacOS/processing-java"
    supercollider_win: "C:\\Program Files\\SuperCollider-3.13.0\\sclang.exe"
  defaults:
    baud_rate: 9600 # bit-rate for Teensy Data
    initial_mode: "wizard" 

# Debug controls
debug:
  keyboard_mappings:
    buttons:
      space: "btn1"    # Space bar simulates dbtn
      z: "btn2"       # Z key simulates pbtn1
      x: "btn3"       # X key simulates pbtn4
    pots:
      q:               # Hold Q and use up/down for pot1
        type: "pot1"
        increment_key: "up"
        decrement_key: "down"
      w:               # Hold W and use up/down for pot2
        type: "pot2"
        increment_key: "up"
        decrement_key: "down"
      e:               # Hold E and use up/down for pot3
        type: "pot3"
        increment_key: "up"
        decrement_key: "down"

modes:
  wizard:
    description: "Wizard mode with fireballs and magic missiles"
    processing:
      sketch: "wizardcore"
      commands:
        fireball: "/fireball"
        missile: "/missile"
        pot_control: "/potControl"
    supercollider:
      script: "wizardcore.scd"
      commands:
        kick: "/kick"
        sine: "/sine_t"
    controls:
      buttons:
        btn1:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/sine_t"
              params: [440]
            - target: "processing"
              command: "/missile"
              params: [3]
        btn2:
          type: "effect"
          actions:
            - target: "supercollider"
              command: "/kick"
              params: [300]
            - target: "processing"
              command: "/fireball"
              params: [5]
      pots:
        pot1:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [0]
        pot2:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [1]
        pot3:
          type: "control"
          target: "processing"
          command: "/potControl"
          params: [2]
  ripple-ring:
    description: "Visual ripples with modular synthesis"
    processing:
      sketch: "RippleRing"
      commands:
        synth_select: "/synth/select"
        mode_toggle: "/mode/global"
    supercollider:
      script: "ripple-ring.scd"
      commands:
        synth_control: "/synthControl"
    controls:
      buttons:
        btn1:
          type: "effect"
          actions:
            - target: "processing"
              command: "/mode/global"
              params: [1]
            - target: "supercollider"
              command: "/synthControl"
              params: [0, 1, "fmSynth", 440, 0.5, 0]
        btn2:
          type: "effect"
          actions:
            - target: "processing"
              command: "/synth/select"
              params: [-1]
            - target: "supercollider"
              command: "/synthControl"
              params: [1, 1, "granular", 220, 0.5, 0]
        btn3:
          type: "effect"
          actions:
            - target: "processing"
              command: "/synth/select"
              params: [1]
            - target: "supercollider"
              command: "/synthControl"
              params: [2, 1, "drone", 110, 0.5, 0]
      pots:
        pot1:
          type: "control"
          target: "processing"
          command: "/pot/1"
          params: [0]  # Make sure this is sending a float value
        pot2:
          type: "control"
          target: "processing"
          command: "/pot/2"
          params: [0]  # Make sure this is sending a float value
        pot3:
          type: "control"
          target: "processing"
          command: "/pot/3"
          params: [0]  # Make sure this is sending a float value